name: Generar M3U

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    paths:
      - "canales.json"
      - "scripts/convertir-a-m3u.js"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Convertir JSON a M3U
        run: node scripts/convertir-a-m3u.js

      - name: Commit y subir cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add canales.m3u
          git diff --cached --quiet || git commit -m "Actualiza canales.m3u"
          git push