name: Actualizar README automáticamente

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    paths:
      - "canales.json"
      - "scripts/generar-listas-readme.js"
  workflow_dispatch:

jobs:
  actualizar-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Importante para evitar problemas de historial al hacer push

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependencias
        run: npm install node-fetch@3

      - name: Ejecutar script
        run: node scripts/generar-listas-readme.js

      - name: Commit y push cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add README.md
          
          # Verificar si hay cambios antes de proceder
          if git diff --cached --quiet; then
            echo "No hay cambios en el README.md, saltando commit."
            exit 0
          fi

          git commit -m "Actualizar listas de canales disponibles"
          
          # Sincronizar con el remoto para evitar conflictos de "non-fast-forward"
          git pull --rebase origin main
          git push origin main
